<?php

/* * **********************************************************
  Filename:  getMessage.php
  Version: 1.0
  Author: Sean Watkins
  Created: 4/18/2006

  Description:  Gets the message from id and returns the html code to
  display that message.

  Dependencies:	htmlfunctons.php
  define_select.php
  buttons.php

  Version History:
  1.0 - 4/18/2006 - Sean Watkins:
 * First release.

 * ************************************************************ */
include("../includes/setup.php");
include("../includes/htmlfunctions.php");
include("../includes/define_select.php");
include("../includes/buttons.php");

$msgid = $_REQUEST["id"];
$type = $_REQUEST["type"];

if (!isset($type)) {
    $query = "SELECT msg_type FROM webedi_messages WHERE PK_id=$msgid";
    $mysql->query($query);
    if ($mysql->good()) {
        $type = $mysql->getRowValue(0);
    }
}
$mysql->query("SELECT FK_tp_profile,message_dir FROM webedi_messages WHERE PK_id=$msgid");
$arry = $mysql->getRowAsArray();
$tp = $arry["FK_tp_profile"];

$p = $_REQUEST["print"];
if ($p == "true") {
    $printing = true;
} else {
    $printing = false;
}

$c = $_REQUEST["csv"];
if ($c == "true") {
    $csv = true;
} else {
    $csv = false;
}

$fv = $_REQUEST["fullview"];
if ($fv == "true") {
    $fullview = true;
} else {
    $fullview = false;
}

$userdata = $session->begin("getting message id: " . $msgid . " type: $type");

$form = formInstance($type, $msgid);
if ($form == null) {
    die(xmlWrapper("The message you are wanting to view is not available.", "error"));
}

// Remove Unread bit
$query = "UPDATE webedi_messages SET flag_msg_state = flag_msg_state & 510 WHERE PK_id = $msgid";
$mysql->query($query);
$query = "UPDATE webedi_messages SET flag_msg_state = flag_msg_state | 128 WHERE PK_id = $msgid";
$mysql->query($query);

if ($csv) {
    $output = $form->getCSV($msgid);
} else {
    $output = $form->getHTML((!$fullview || $printing || ($arry["message_dir"] == "sent")));
}


$query = "SELECT message_dir,flag_msg_state,msg_FK_id,webedi_lp.weblogin,inserted_datetime,sent_datetime,msg_type FROM webedi_messages INNER JOIN webedi_lp ON webedi_messages.FK_userid = webedi_lp.userid WHERE PK_id=$msgid";
$mysql->query($query);
$message = $mysql->getRowAsArray();

if (!hasFormPermissions($type, "read", $tp)) {
    die(xmlWrapper("You do not have access to view this form.", "error"));
}

if ($message["msg_FK_id"] != "" && !$printing) {
    $query = "SELECT * FROM webedi_messages WHERE PK_id=" . $message["msg_FK_id"];
    $mysql->query($query);
    if ($mysql->good()) {
        $gen = $mysql->getRowAsArray();
        $msg = "Generated from - Message ID: " . $gen["PK_id"] . ", Document ID: " . $gen["msg_type"] . ", Date/Time: " . $gen["inserted_datetime"] . "<br>
		        Generated by User ID: " . $message["weblogin"] . " on " . $message["inserted_datetime"];
        if ($message["message_dir"] == "sent")
            $msg .= "<br>
			         Message sent on: " . $message["sent_datetime"];
    } else {
        $msg = "Generated from:  Could not find original message information.";
    }
    $output = "<div class=\"msg_header\">
	               <table border=\"0\" cellspacing=\"0\" cellpadding=\"5\">
		       <tr>
		       <td><img src=\"" . _SITE_URL . "ui/images/icon-information.gif\" alt=\"Info\" /></td>
		       <td>$msg</td>
		       </tr>
		       </table>
		       </div>
		       $output";
}

if ($fullview) {
    if ($message["message_dir"] == "") {
        $mysql->query("SELECT message_dir,flag_msg_state,FK_tp_profile,msg_type FROM webedi_messages WHERE PK_id=$msgid");
        $message = $mysql->getRowAsArray();
    }

    $dir = $message["message_dir"];
    $arc = $message["flag_msg_state"];
    if (strpos(strtolower($arc), "archive") > -1)
        $archive = true;
    $buttons = new Buttons($template, "button");
    switch ($dir) {
        case "in":
            $buttons->addButton("icon-compose.gif", "expand_menu('compose_menu',this);", "Compose", true);
            $buttons->addButton("icon-respond.gif", "expand_response(this,'response_menu');", "Generate Response", true);
            $buttons->addButton("icon-reset-message.gif", "resetMessage('$msgid');", "Reset Message");
            break;
        case "out":
            $buttons->addButton("icon-save.gif", "save();", "Save");
            //if($type != "sale")
            $buttons->addButton("icon-send.gif", "send('$msgid');", "Send");
            break;
        case "sent":
            $buttons->addButton("icon-compose.gif", "expand_menu('compose_menu',this);", "Compose", true);
            $buttons->addButton("icon-restage.gif", "restage($msgid);", "Restage");
            break;
    }
    if (!$archive)
        $buttons->addButton("icon-add-archive.gif", "archive('$msgid');", "Archive");
    if ($message["msg_type"] == "856") {
        $buttons->addButton("icon-print.gif", "expand_menu('print_856_menu',this);", "Print", true);
    } else {
        $buttons->addButton("icon-print.gif", "print('$msgid');", "Print");
    }
    if ($message["msg_type"] == "850") {
        $buttons->addButton("icon-import-export.gif", "expand_response(this,'po_options');", "Options", true);
    }
    if ($message["msg_type"] == "856") {
        $buttons->addButton("icon-import-export.gif", "expand_response(this,'asn_options');", "Options", true);
    }
    $buttons->addButton("icon-close.gif", "closeMessage();", "Close");

    $output = $buttons->parse() . "<div id=\"message_content\">$output</div>";
}

if (!$printing && !$csv)
    $output = xmlWrapper($output);
elseif ($printing) {
    $output = "<html><header></header><body onload=\"window.parent.responsePrint();\">$output</body></html>";
}

print $output;
